# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BoberOS
                                 A QGIS plugin
 This plugin manages data making it easier to import and actualize it on local disk
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-09
        copyright            : (C) 2025 by Bartosz Łęczycki
        email                : bartosz.leczycki98@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    from .bober_os import BoberOS
    return BoberOS(iface)
